"use client";

import { useState } from "react";
import Link from "next/link";
import { FolderKanban, Search, Plus, Sparkles, Filter, CheckCircle2 } from "lucide-react";
import { Button, Card, Badge } from "@useaxiom/ui";

interface Project {
  id: string;
  name: string;
  category: string;
  description: string;
  status: "progress" | "proposed" | "completed";
  progress: number;
  health: "on_track" | "at_risk" | "review";
  tasksDone: number;
  tasksTotal: number;
}

export default function ProjectsPage() {
  const [search, setSearch] = useState("");
  const [activeTab, setActiveTab] = useState<"all" | "progress" | "proposed" | "completed">("all");

  const [projects] = useState<Project[]>([
    {
      id: "axiom-platform-setup",
      name: "Axiom Platform Setup",
      category: "Core Infrastructure",
      description: "Initialize workspace configurations, setup local dev containers, and configure NestJS base modules.",
      status: "progress",
      progress: 75,
      health: "on_track",
      tasksDone: 3,
      tasksTotal: 4
    },
    {
      id: "q3-marketing-launch",
      name: "Q3 Marketing Launch",
      category: "Product Growth",
      description: "Deconstruct goal into atomic social media and creative asset tasks, and assign to marketing resource pool.",
      status: "proposed",
      progress: 0,
      health: "review",
      tasksDone: 0,
      tasksTotal: 3
    },
    {
      id: "legacy-db-migration",
      name: "Legacy Database Migration",
      category: "Database Ops",
      description: "Migrate historical organization records from old SQL Dump into Postgres Prisma schema.",
      status: "completed",
      progress: 100,
      health: "on_track",
      tasksDone: 8,
      tasksTotal: 8
    }
  ]);

  const filteredProjects = projects.filter(project => {
    const matchesSearch = project.name.toLowerCase().includes(search.toLowerCase()) || 
                          project.category.toLowerCase().includes(search.toLowerCase());
    const matchesTab = activeTab === "all" ? true : project.status === activeTab;
    return matchesSearch && matchesTab;
  });

  const getHealthBadge = (health: string) => {
    switch (health) {
      case "on_track":
        return <span className="text-xs text-emerald-400 font-semibold flex items-center gap-1">🟢 On Track</span>;
      case "at_risk":
        return <span className="text-xs text-red-400 font-semibold flex items-center gap-1">🔴 At Risk</span>;
      case "review":
      default:
        return <span className="text-xs text-amber-400 font-semibold flex items-center gap-1">⚠️ Needs Review</span>;
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-zinc-100">Projects Workspace</h1>
          <p className="text-zinc-400 text-sm mt-1">Monitor the execution states and goals generated by the planner.</p>
        </div>
        <Button variant="primary" size="sm" className="rounded-xl shadow-lg shadow-purple-500/10 cursor-pointer">
          <Plus className="w-4 h-4" />
          <span>New Project Goal</span>
        </Button>
      </div>

      {/* Filters and Search Bar */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-zinc-900/20 p-4 rounded-2xl border border-zinc-900">
        {/* Status Tabs */}
        <div className="flex bg-zinc-950/60 p-1.5 rounded-xl border border-zinc-800/80 gap-1 overflow-x-auto w-full md:w-auto">
          {[
            { id: "all", label: "All Campaigns" },
            { id: "progress", label: "In Progress" },
            { id: "proposed", label: "Awaiting Review" },
            { id: "completed", label: "Completed" }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all whitespace-nowrap cursor-pointer ${
                activeTab === tab.id
                  ? "bg-zinc-800 text-zinc-100 shadow-sm border border-zinc-700/50"
                  : "text-zinc-400 hover:text-zinc-200 border border-transparent"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Search */}
        <div className="flex items-center gap-2 bg-zinc-950 border border-zinc-850 px-3.5 py-2 rounded-xl w-full md:w-80">
          <Search className="w-4 h-4 text-zinc-500" />
          <input
            type="text"
            value={search}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)}
            placeholder="Search campaigns..."
            className="bg-transparent text-xs text-zinc-200 outline-none w-full placeholder-zinc-500"
          />
        </div>
      </div>

      {/* Projects Grid */}
      {filteredProjects.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredProjects.map((project) => (
            <Card key={project.id} className="flex flex-col h-full hover:border-zinc-700/80 transition-all duration-300">
              <div className="flex-1 space-y-4">
                <div className="flex justify-between items-start">
                  <div>
                    <span className="text-[10px] font-bold text-purple-400 uppercase tracking-widest bg-purple-500/5 px-2 py-0.5 rounded border border-purple-500/10">
                      {project.category}
                    </span>
                    <h3 className="font-bold text-lg text-zinc-200 mt-2 hover:text-purple-400 transition-colors">
                      <Link href={`/projects/${project.id}`}>{project.name}</Link>
                    </h3>
                  </div>
                  <Badge variant={project.status}>
                    {project.status === "progress" && "Active"}
                    {project.status === "proposed" && "Proposed"}
                    {project.status === "completed" && "Completed"}
                  </Badge>
                </div>

                <p className="text-xs text-zinc-400 leading-relaxed truncate-2-lines min-h-[40px]">
                  {project.description}
                </p>

                {/* Progress */}
                <div className="space-y-1.5 pt-2">
                  <div className="flex justify-between text-xs font-semibold text-zinc-400">
                    <span>Task Execution</span>
                    <span className="text-zinc-200">{project.progress}%</span>
                  </div>
                  <div className="w-full bg-zinc-850 h-1.5 rounded-full overflow-hidden">
                    <div
                      className="bg-gradient-to-r from-purple-500 to-indigo-500 h-full rounded-full transition-all duration-500"
                      style={{ width: `${project.progress}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Card Footer */}
              <div className="mt-6 pt-4 border-t border-zinc-800 flex items-center justify-between">
                {getHealthBadge(project.health)}
                <div className="flex items-center gap-1.5 text-xs text-zinc-400 font-semibold bg-zinc-950 px-2.5 py-1 rounded-lg border border-zinc-850">
                  <span>{project.tasksDone}/{project.tasksTotal} Tasks</span>
                </div>
              </div>
            </Card>
          ))}
        </div>
      ) : (
        <Card className="flex flex-col items-center justify-center text-center py-16">
          <FolderKanban className="w-12 h-12 text-zinc-700 mb-3" />
          <h3 className="text-zinc-300 font-semibold text-sm">No campaigns found</h3>
          <p className="text-zinc-500 text-xs mt-1">Try modifying your keyword search or filters.</p>
        </Card>
      )}
    </div>
  );
}
